# SPDX-FileCopyrightText: 2022 Paul Colby <git@colby.id.au>
# SPDX-License-Identifier: MIT

name: Summary Test Results

author: Paul Colby

description: Summarise TAP (Test Anything Protocol) test results

inputs:
  path:
    description: One or more paths to TAP files
    required: true
    default: '**/*.tap'
  summary-file:
    description: File to append TAP summary to
    required: false

outputs:
  summary-file:
    description: File TAP summary was appended to
    value: ${{ steps.tap.outputs.summary-file }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ runner.temp }}/tap-summary
    - run: |
        set -o errexit -o noclobber -o nounset -o pipefail
        [[ -z "$(shopt globstar 2> /dev/null)" ]] && echo 'Shell does not support globstar' || shopt -s globstar
        : "${SUMMARY_FILE:=$GITHUB_STEP_SUMMARY}"
        echo ${{ inputs.path }} '->' "$SUMMARY_FILE"
        gawk --file "$RUNNER_TEMP/tap-summary/summary.gawk" --sandbox -- ${{ inputs.path }} >> "$SUMMARY_FILE"
        echo "::set-output name=summary-file::$SUMMARY_FILE"
      shell: bash
      env:
        SUMMARY_FILE: ${{ inputs.summary-file }}
      id: tap

branding:
  color: green
  icon: check
