# SPDX-FileCopyrightText: 2022 Paul Colby <git@colby.id.au>
# SPDX-License-Identifier: MIT

name: Summary Test Results

author: Paul Colby

description: Summarise TAP (Test Anything Protocol) test results

inputs:
  path:
    required: true
    default: '**/*.tap'
  summary-file:
    required: false

runs:
  using: composite
  steps:
    - run: |
        set -o errexit -o noclobber -o nounset -o pipefail
        [[ -z "$(shopt globstar 2> /dev/null)" ]] && echo 'Shell does not support globstar' || shopt -s globstar
        : "${SUMMARY_FILE:=$GITHUB_STEP_SUMMARY}"
        echo ${{ inputs.path }} '->' "$SUMMARY_FILE"
        gawk --file test-summary.gawk --sandbox -- ${{ inputs.path }} >> "$SUMMARY_FILE"
      shell: bash
      env:
        SUMMARY_FILE: ${{ inputs.summary-file }}

branding:
  color: green
  icon: check
