# SPDX-FileCopyrightText: 2022 Paul Colby <git@colby.id.au>
# SPDX-License-Identifier: MIT

name: Automatic Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: ./test/test.sh
        shell: bash
    strategy:
      matrix:
        os:
          - macos-10.15
          - macos-11     # aka macos-latest
          - macos-12
          - ubuntu-18.04
          - ubuntu-20.04 # aka ubuntu-latest
          - ubuntu-22.04
          - windows-2019
          - windows-2022 # aka windows-latest
      fail-fast: false
